import {
  Box,
  Text,
  Heading,
  Container,
  VStack,
  FormControl,
  FormLabel,
  Button,
  Input,
  SimpleGrid,
  useToast,
  FormErrorMessage,
} from "@chakra-ui/react"
import { createRef } from "react"
import { useForm } from "react-hook-form"
import { Card } from "../components/cards/Card"
import { useMoralis, useWeb3Contract } from "react-moralis"
import { TokenDropdown } from "../components/dropdown/TokenDropdown"
import { useState } from "react"

import zeroKageLocalAbi from "../contracts/localhost_ZeroKage.json"
import zeroKageGoerliAbi from "../contracts/localhost_ZeroKage.json"
import dexLocalAbi from "../contracts/localhost_DEX.json"
import dexGoerliAbi from "../contracts/goerli_DEX.json"
import { getNetworkName } from "../utils/misc"
import addressList from "../contracts/addresses.json"
import { ethers } from "ethers"
import { WaitingModal } from "../components/modals/WaitingModal"

export const Swap = () => {
  const { account, chainId } = useMoralis()
  const networkName = getNetworkName(chainId)
  const toast = useToast()
  const zKageAbi =
    networkName && networkName === "goerli"
      ? zeroKageGoerliAbi
      : zeroKageLocalAbi

  const dexAbi =
    networkName && networkName === "goerli" ? dexGoerliAbi : dexLocalAbi

  const chainIdString = chainId && parseInt(chainId)
  const zKageAddress = chainIdString
    ? addressList[chainIdString]["ZeroKage"]
    : null
  const dexAddress = chainIdString ? addressList[chainIdString]["DEX"][0] : null

  const [timer, setTimer] = useState(null)
  const [isConfirming, setIsConfirming] = useState(false)

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm()

  const sendTokenRef = createRef()
  const receiveTokenRef = createRef()

  const { runContractFunction, isLoading, isFetching } = useWeb3Contract()
  const apiParams = { abi: dexAbi, contractAddress: dexAddress }

  //****************** EVENT HANDLER FUNCTIONS *****************/

  /**
   * @notice event handler updates the receive token value when send token value is changed
   * @dev tokens calculated as per constant AMM formula in DEX contract
   * @param {*} e event
   * @param {*} tokenRef send currency token reference
   */
  const onSendTokenValueChanged = (e, tokenRef) => {
    const value = e.target.value
    const sendToken = tokenRef?.current?.value

    clearTimeout(timer)
    const newTimer = setTimeout(() => {
      console.log("toke ref current val in send", sendToken)
      sendToken === "ETH"
        ? EthToToken("receive", value)
        : TokenToEth("receive", value)
    }, 500)

    setTimer(newTimer)
  }

  /**
   * @notice event handler updates the send token value when receive token value is changed
   * @dev tokens calculated as per constant AMM formula in DEX contract
   * @param {*} e event
   * @param {*} tokenRef receive currency token reference
   */
  const onReceiveTokenValueChanged = (e, tokenRef) => {
    const value = e.target.value
    const receiveToken = tokenRef?.current?.value
    clearTimeout(timer)
    const newTimer = setTimeout(() => {
      console.log("toke ref current val in receive", receiveToken)
      receiveToken === "ETH"
        ? EthToToken("send", value)
        : TokenToEth("send", value)
    }, 500)

    setTimer(newTimer)
  }
  //----------------------------------------------------//

  //**************** CALLBACK FUNCTIONS ******************** */

  /**
   * @notice send success notification to user once txn receipt is generated
   * @param {any} values returns transaction response
   */
  const successSwapHandler = async (response) => {
    setIsConfirming(true)

    // wait for 1 block confirmation
    const txnReceipt = await response.wait(1)
    setIsConfirming(false)

    // insert success notification
    toast({
      title: `Success`,
      status: "success",
      description: `Swap completed. Txn hash ${txnReceipt.transactionHash}`,
      isClosable: true,
      duration: 9000,
    })
  }

  /**
   * @notice handles errors generated by any API function
   * @param {any} e error description
   */
  const errorHandler = (e) => {
    console.log(e.message)
    // insert error notification here
    toast({
      title: `Error`,
      status: "error",
      description: { e },
      isClosable: true,
      duration: 9000,
    })
  }
  //-----------------------------------------------------------//

  //********************** API FUNCTIONS ********************//

  /**
   * @notice executes a swap between tokens based on constant AMM DEX logic
   * @dev Call 'ethToZeroKage' function if we are sending Eth. 'zeroKageToEth' if we are sending 0Kage
   * @param {any} values token values of each token in swap pair
   */
  const onSubmitSwap = (values) => {
    console.log("values", values)
    console.log("send token", sendTokenRef.current?.value)
    console.log("receive token", receiveTokenRef.current?.value)

    const sendEth = sendTokenRef?.current?.value === "ETH"
    const swapParams = {
      ...apiParams,
      functionName: sendEth ? "ethToZeroKage" : "zeroKageToEth",
      params: sendEth
        ? {}
        : { zeroKageTokens: ethers.utils.parseEther(values.send) },
      msgValue: sendEth ? ethers.utils.parseEther(values.send) : null,
    }

    console.log("swap params", swapParams)

    runContractFunction({
      params: swapParams,
      onSuccess: successSwapHandler,
      onError: errorHandler,
    })
  }

  /**
   * @notice function calculates # of $ETH tokens that need to be swapped for a user-specified $0KAGE
   * @dev set a timeout of 0.5 seconds after user stops typing -> query price API only aftet this using setTimeout
   * @param {string} token token receive - receive field should be set, send - send field should be set
   * @param {string} value # of tokens in ether terms - use parseEther to convert to wei
   */
  const TokenToEth = (token, value) => {
    console.log("Token->Eth conversion..")
    console.log("token is", token)
    const priceParams = {
      ...apiParams,
      params: { numTokens: ethers.utils.parseEther(value) },
      functionName: "getSwappableEth",
    }
    // runContractFunction()

    runContractFunction({
      params: priceParams,
      onSuccess: (value) => setValue(token, ethers.utils.formatEther(value)),
      onError: (e) => console.log(e),
    })
  }

  /**
   * @notice function calculates # of $0Kage tokens that need to be exchanged for a user-specified $ETH
   * @dev set a timeout of 0.5 seconds after user stops typing -> query price API only aftet this using setTimeout
   * @param {string} token token receive - receive field should be set, send - send field should be set
   * @param {string} value # of eth - use parseEther to convert to wei
   */
  const EthToToken = (token, value) => {
    console.log("Eth->Token conversion..")
    console.log("token is", token)

    console.log("dex abi", dexAbi)
    console.log("dex address", dexAddress)
    const priceParams = {
      ...apiParams,
      params: { numEth: ethers.utils.parseEther(value) },
      functionName: "getSwappableTokens",
    }

    runContractFunction({
      params: priceParams,
      onSuccess: (value) => setValue(token, ethers.utils.formatEther(value)),
      onError: (e) => console.log(e),
    })
  }

  return (
    <Box as="section" height="100vh" width={1200} overflowY="auto" mx="auto">
      {(!account || !chainId) && (
        <Heading as="h2" fontSize="2xl" my="auto" textAlign="10" mt="10">
          Please connect your wallet
        </Heading>
      )}

      {chainId && account && (
        <Container>
          <Card mt="10" width="400">
            <Text fontSize="md" fontWeight="bold">
              Swap
            </Text>
            <form onSubmit={handleSubmit(onSubmitSwap)}>
              <FormControl mt="10">
                <VStack spacing="4">
                  <SimpleGrid columns={3} spacingX="10px">
                    <FormLabel>Send</FormLabel>
                    <Input
                      placeholder="Enter amt in Eth terms"
                      onInput={(e) => onSendTokenValueChanged(e, sendTokenRef)}
                      {...register("send", {
                        required: {
                          value: true,
                          message: "Specify amount to send",
                        },
                      })}
                    />
                    <TokenDropdown
                      tokenList={["ETH", "0KAGE"]}
                      ref={sendTokenRef}
                    />
                  </SimpleGrid>
                  <SimpleGrid columns={3} spacingX="6px">
                    <FormLabel>Receive</FormLabel>
                    <Input
                      onInput={(e) =>
                        onReceiveTokenValueChanged(e, receiveTokenRef)
                      }
                      placeholder="Enter amt in Eth terms"
                      {...register("receive", {
                        required: {
                          value: true,
                          message: "Specify amount to receive",
                        },
                      })}
                    />
                    <TokenDropdown
                      tokenList={["0KAGE", "ETH"]}
                      ref={receiveTokenRef}
                    />
                  </SimpleGrid>
                </VStack>
              </FormControl>
              <Button
                type="submit"
                colorScheme="blue"
                variant="solid"
                mt="10"
                width="50%">
                Swap
              </Button>
            </form>
          </Card>
          <WaitingModal
            isOpen={isConfirming || isLoading}
            network={networkName}
          />
        </Container>
      )}
    </Box>
  )
}
